[package]
name = "opti_space"
version = "0.1.0"
authors = ["Knepsi <git@lp-kb.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
stl_io = "0.6.0"